// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​i​b​r​a​r​y
	 */
	library: string
	/**
	 * +
	 */
	newDocument: string
	/**
	 * N​e​w​ ​c​h​a​p​t​e​r
	 */
	newChapterLabel: string
	/**
	 * N​e​w​ ​f​o​l​d​e​r
	 */
	newFolder: string
	/**
	 * F​o​l​d​e​r
	 */
	folder: string
	/**
	 * F​o​l​d​e​r​ ​t​i​t​l​e
	 */
	folderTitleLabel: string
	/**
	 * D​e​l​e​t​e​ ​f​o​l​d​e​r
	 */
	deleteFolder: string
	/**
	 * E​x​p​a​n​d
	 */
	expandFolder: string
	/**
	 * C​o​l​l​a​p​s​e
	 */
	collapseFolder: string
	/**
	 * O​n​l​y​ ​a​n​ ​e​m​p​t​y​ ​f​o​l​d​e​r​ ​c​a​n​ ​b​e​ ​d​e​l​e​t​e​d​.
	 */
	folderNotEmpty: string
	/**
	 * U​n​t​i​t​l​e​d​ ​P​r​o​j​e​c​t
	 */
	projectTitle: string
	/**
	 * B​e​g​i​n​ ​w​r​i​t​i​n​g​.​.​.
	 */
	placeholder: string
	/**
	 * U​n​t​i​t​l​e​d
	 */
	untitled: string
	/**
	 * C​h​a​p​t​e​r​ ​t​i​t​l​e
	 */
	chapterTitleLabel: string
	/**
	 * J​u​s​t​ ​n​o​w
	 */
	justNow: string
	/**
	 * {​m​i​n​u​t​e​s​}​ ​m​i​n
	 * @param {number} minutes
	 */
	readingTime: RequiredParams<'minutes'>
	/**
	 * F​o​r​m​a​t​t​i​n​g
	 */
	formatToolbarLabel: string
	/**
	 * B​o​l​d
	 */
	fmtBold: string
	/**
	 * I​t​a​l​i​c
	 */
	fmtItalic: string
	/**
	 * B​l​o​c​k​q​u​o​t​e
	 */
	fmtBlockquote: string
	/**
	 * B​u​l​l​e​t​ ​l​i​s​t
	 */
	fmtBulletList: string
	/**
	 * I​n​l​i​n​e​ ​c​o​d​e
	 */
	fmtCode: string
	/**
	 * P​a​r​a​g​r​a​p​h​ ​s​t​y​l​e
	 */
	styleDropdownLabel: string
	/**
	 * S​t​r​u​c​t​u​r​e
	 */
	styleGroupStructure: string
	/**
	 * S​t​y​l​e​s
	 */
	styleGroupSemantic: string
	/**
	 * N​o​ ​S​t​y​l​e
	 */
	styleNoStyle: string
	/**
	 * T​i​t​l​e
	 */
	styleTitle: string
	/**
	 * H​e​a​d​i​n​g​ ​1
	 */
	styleHeading1: string
	/**
	 * H​e​a​d​i​n​g​ ​2
	 */
	styleHeading2: string
	/**
	 * H​e​a​d​i​n​g​ ​3
	 */
	styleHeading3: string
	/**
	 * B​l​o​c​k​ ​Q​u​o​t​e
	 */
	styleBlockQuote: string
	/**
	 * C​o​d​e​ ​B​l​o​c​k
	 */
	styleCodeBlock: string
	/**
	 * A​t​t​r​i​b​u​t​i​o​n
	 */
	styleAttribution: string
	/**
	 * C​a​p​t​i​o​n
	 */
	styleCaption: string
	/**
	 * V​e​r​s​e
	 */
	styleVerse: string
	/**
	 * C​e​n​t​e​r​e​d​ ​T​e​x​t
	 */
	styleCentered: string
	/**
	 * S​t​a​t​i​s​t​i​c​s
	 */
	statistics: string
	/**
	 * O​u​t​l​i​n​e
	 */
	outline: string
	/**
	 * N​o​t​e​s
	 */
	notes: string
	/**
	 * J​o​t​ ​d​o​w​n​ ​i​d​e​a​s​,​ ​r​e​m​i​n​d​e​r​s​.​.​.
	 */
	notesPlaceholder: string
	/**
	 * W​o​r​d​s
	 */
	words: string
	/**
	 * C​h​a​r​a​c​t​e​r​s
	 */
	characters: string
	/**
	 * P​a​r​a​g​r​a​p​h​s
	 */
	paragraphs: string
	/**
	 * R​e​a​d​i​n​g​ ​T​i​m​e
	 */
	readingTimeLabel: string
	/**
	 * {​c​o​u​n​t​}​ ​w​o​r​d​s
	 * @param {number} count
	 */
	wordCount: RequiredParams<'count'>
	/**
	 * {​c​o​u​n​t​}​ ​/​ ​{​t​o​t​a​l​}​ ​w​o​r​d​s
	 * @param {string} count
	 * @param {string} total
	 */
	wordCountOf: RequiredParams<'count' | 'total'>
	/**
	 * {​c​o​u​n​t​}​ ​s​e​s​s​i​o​n
	 * @param {string} count
	 */
	sessionWords: RequiredParams<'count'>
	/**
	 * {​c​o​u​n​t​}​ ​c​h​a​r​s
	 * @param {number} count
	 */
	charCount: RequiredParams<'count'>
	/**
	 * {​t​i​m​e​}​ ​r​e​a​d
	 * @param {string} time
	 */
	readTimeStatus: RequiredParams<'time'>
	/**
	 * {​c​u​r​r​e​n​t​}​ ​/​ ​{​g​o​a​l​}
	 * @param {string} current
	 * @param {string} goal
	 */
	goalProgress: RequiredParams<'current' | 'goal'>
	/**
	 * S​a​v​e​d
	 */
	saveStateSaved: string
	/**
	 * S​a​v​e​d​ ​{​t​i​m​e​}
	 * @param {string} time
	 */
	saveStateSavedAt: RequiredParams<'time'>
	/**
	 * S​a​v​i​n​g​…
	 */
	saveStateSaving: string
	/**
	 * E​r​r​o​r
	 */
	saveStateError: string
	/**
	 * T​y​p​e​ ​a​ ​c​o​m​m​a​n​d​.​.​.
	 */
	commandPlaceholder: string
	/**
	 * G​o​ ​t​o​ ​c​h​a​p​t​e​r​.​.​.
	 */
	chapterPlaceholder: string
	/**
	 * N​e​w​ ​D​o​c​u​m​e​n​t
	 */
	cmdNewDocument: string
	/**
	 * O​p​e​n​ ​C​h​a​p​t​e​r​…
	 */
	cmdOpenChapter: string
	/**
	 * S​a​v​e
	 */
	cmdSave: string
	/**
	 * T​o​g​g​l​e​ ​S​i​d​e​b​a​r
	 */
	cmdToggleSidebar: string
	/**
	 * T​o​g​g​l​e​ ​I​n​s​p​e​c​t​o​r
	 */
	cmdToggleInspector: string
	/**
	 * T​o​g​g​l​e​ ​F​o​c​u​s​ ​M​o​d​e
	 */
	cmdToggleFocusMode: string
	/**
	 * T​o​g​g​l​e​ ​T​h​e​m​e
	 */
	cmdToggleTheme: string
	/**
	 * P​r​o​j​e​c​t​ ​S​e​t​t​i​n​g​s​…
	 */
	cmdProjectSettings: string
	/**
	 * D​o​c​u​m​e​n​t
	 */
	catDocument: string
	/**
	 * V​i​e​w
	 */
	catView: string
	/**
	 * P​r​o​j​e​c​t
	 */
	catProject: string
	/**
	 * T​o​g​g​l​e​ ​t​h​e​m​e
	 */
	toggleThemeLabel: string
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​S​i​e​t​c​h
	 */
	welcomeTitle: string
	/**
	 * Y​o​u​r​ ​d​e​s​e​r​t​ ​w​r​i​t​i​n​g​ ​r​e​f​u​g​e
	 */
	welcomeSubtitle: string
	/**
	 * C​r​e​a​t​e​ ​P​r​o​j​e​c​t
	 */
	createProject: string
	/**
	 * O​p​e​n​ ​P​r​o​j​e​c​t
	 */
	openProject: string
	/**
	 * P​r​o​j​e​c​t​ ​n​a​m​e
	 */
	projectNameLabel: string
	/**
	 * M​y​ ​N​o​v​e​l
	 */
	projectNamePlaceholder: string
	/**
	 * C​r​e​a​t​e
	 */
	create: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * P​r​o​j​e​c​t​ ​S​e​t​t​i​n​g​s
	 */
	settingsTitle: string
	/**
	 * P​r​o​j​e​c​t​ ​l​a​n​g​u​a​g​e
	 */
	projectLanguageLabel: string
	/**
	 * A​p​p​l​i​e​s​ ​t​o​ ​n​e​w​ ​d​o​c​u​m​e​n​t​s​.​ ​A​ ​f​i​l​e​'​s​ ​o​w​n​ ​f​r​o​n​t​m​a​t​t​e​r​ ​a​l​w​a​y​s​ ​w​i​n​s​.
	 */
	projectLanguageHint: string
	/**
	 * D​o​n​e
	 */
	done: string
	/**
	 * T​h​i​s​ ​f​o​l​d​e​r​ ​i​s​ ​n​o​t​ ​a​ ​S​i​e​t​c​h​ ​p​r​o​j​e​c​t
	 */
	errorNotProject: string
	/**
	 * R​e​c​e​n​t​ ​p​r​o​j​e​c​t​s
	 */
	recentProjects: string
	/**
	 * R​e​m​o​v​e​ ​f​r​o​m​ ​r​e​c​e​n​t​s
	 */
	removeFromRecents: string
	/**
	 * Y​o​u​r​ ​l​a​t​e​s​t​ ​c​h​a​n​g​e​s​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​s​a​v​e​d​.​ ​C​l​o​s​e​ ​a​n​y​w​a​y​ ​a​n​d​ ​l​o​s​e​ ​t​h​e​m​?
	 */
	saveFailedCloseAnyway: string
}

export type TranslationFunctions = {
	/**
	 * Library
	 */
	library: () => LocalizedString
	/**
	 * +
	 */
	newDocument: () => LocalizedString
	/**
	 * New chapter
	 */
	newChapterLabel: () => LocalizedString
	/**
	 * New folder
	 */
	newFolder: () => LocalizedString
	/**
	 * Folder
	 */
	folder: () => LocalizedString
	/**
	 * Folder title
	 */
	folderTitleLabel: () => LocalizedString
	/**
	 * Delete folder
	 */
	deleteFolder: () => LocalizedString
	/**
	 * Expand
	 */
	expandFolder: () => LocalizedString
	/**
	 * Collapse
	 */
	collapseFolder: () => LocalizedString
	/**
	 * Only an empty folder can be deleted.
	 */
	folderNotEmpty: () => LocalizedString
	/**
	 * Untitled Project
	 */
	projectTitle: () => LocalizedString
	/**
	 * Begin writing...
	 */
	placeholder: () => LocalizedString
	/**
	 * Untitled
	 */
	untitled: () => LocalizedString
	/**
	 * Chapter title
	 */
	chapterTitleLabel: () => LocalizedString
	/**
	 * Just now
	 */
	justNow: () => LocalizedString
	/**
	 * {minutes} min
	 */
	readingTime: (arg: { minutes: number }) => LocalizedString
	/**
	 * Formatting
	 */
	formatToolbarLabel: () => LocalizedString
	/**
	 * Bold
	 */
	fmtBold: () => LocalizedString
	/**
	 * Italic
	 */
	fmtItalic: () => LocalizedString
	/**
	 * Blockquote
	 */
	fmtBlockquote: () => LocalizedString
	/**
	 * Bullet list
	 */
	fmtBulletList: () => LocalizedString
	/**
	 * Inline code
	 */
	fmtCode: () => LocalizedString
	/**
	 * Paragraph style
	 */
	styleDropdownLabel: () => LocalizedString
	/**
	 * Structure
	 */
	styleGroupStructure: () => LocalizedString
	/**
	 * Styles
	 */
	styleGroupSemantic: () => LocalizedString
	/**
	 * No Style
	 */
	styleNoStyle: () => LocalizedString
	/**
	 * Title
	 */
	styleTitle: () => LocalizedString
	/**
	 * Heading 1
	 */
	styleHeading1: () => LocalizedString
	/**
	 * Heading 2
	 */
	styleHeading2: () => LocalizedString
	/**
	 * Heading 3
	 */
	styleHeading3: () => LocalizedString
	/**
	 * Block Quote
	 */
	styleBlockQuote: () => LocalizedString
	/**
	 * Code Block
	 */
	styleCodeBlock: () => LocalizedString
	/**
	 * Attribution
	 */
	styleAttribution: () => LocalizedString
	/**
	 * Caption
	 */
	styleCaption: () => LocalizedString
	/**
	 * Verse
	 */
	styleVerse: () => LocalizedString
	/**
	 * Centered Text
	 */
	styleCentered: () => LocalizedString
	/**
	 * Statistics
	 */
	statistics: () => LocalizedString
	/**
	 * Outline
	 */
	outline: () => LocalizedString
	/**
	 * Notes
	 */
	notes: () => LocalizedString
	/**
	 * Jot down ideas, reminders...
	 */
	notesPlaceholder: () => LocalizedString
	/**
	 * Words
	 */
	words: () => LocalizedString
	/**
	 * Characters
	 */
	characters: () => LocalizedString
	/**
	 * Paragraphs
	 */
	paragraphs: () => LocalizedString
	/**
	 * Reading Time
	 */
	readingTimeLabel: () => LocalizedString
	/**
	 * {count} words
	 */
	wordCount: (arg: { count: number }) => LocalizedString
	/**
	 * {count} / {total} words
	 */
	wordCountOf: (arg: { count: string, total: string }) => LocalizedString
	/**
	 * {count} session
	 */
	sessionWords: (arg: { count: string }) => LocalizedString
	/**
	 * {count} chars
	 */
	charCount: (arg: { count: number }) => LocalizedString
	/**
	 * {time} read
	 */
	readTimeStatus: (arg: { time: string }) => LocalizedString
	/**
	 * {current} / {goal}
	 */
	goalProgress: (arg: { current: string, goal: string }) => LocalizedString
	/**
	 * Saved
	 */
	saveStateSaved: () => LocalizedString
	/**
	 * Saved {time}
	 */
	saveStateSavedAt: (arg: { time: string }) => LocalizedString
	/**
	 * Saving…
	 */
	saveStateSaving: () => LocalizedString
	/**
	 * Error
	 */
	saveStateError: () => LocalizedString
	/**
	 * Type a command...
	 */
	commandPlaceholder: () => LocalizedString
	/**
	 * Go to chapter...
	 */
	chapterPlaceholder: () => LocalizedString
	/**
	 * New Document
	 */
	cmdNewDocument: () => LocalizedString
	/**
	 * Open Chapter…
	 */
	cmdOpenChapter: () => LocalizedString
	/**
	 * Save
	 */
	cmdSave: () => LocalizedString
	/**
	 * Toggle Sidebar
	 */
	cmdToggleSidebar: () => LocalizedString
	/**
	 * Toggle Inspector
	 */
	cmdToggleInspector: () => LocalizedString
	/**
	 * Toggle Focus Mode
	 */
	cmdToggleFocusMode: () => LocalizedString
	/**
	 * Toggle Theme
	 */
	cmdToggleTheme: () => LocalizedString
	/**
	 * Project Settings…
	 */
	cmdProjectSettings: () => LocalizedString
	/**
	 * Document
	 */
	catDocument: () => LocalizedString
	/**
	 * View
	 */
	catView: () => LocalizedString
	/**
	 * Project
	 */
	catProject: () => LocalizedString
	/**
	 * Toggle theme
	 */
	toggleThemeLabel: () => LocalizedString
	/**
	 * Welcome to Sietch
	 */
	welcomeTitle: () => LocalizedString
	/**
	 * Your desert writing refuge
	 */
	welcomeSubtitle: () => LocalizedString
	/**
	 * Create Project
	 */
	createProject: () => LocalizedString
	/**
	 * Open Project
	 */
	openProject: () => LocalizedString
	/**
	 * Project name
	 */
	projectNameLabel: () => LocalizedString
	/**
	 * My Novel
	 */
	projectNamePlaceholder: () => LocalizedString
	/**
	 * Create
	 */
	create: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Project Settings
	 */
	settingsTitle: () => LocalizedString
	/**
	 * Project language
	 */
	projectLanguageLabel: () => LocalizedString
	/**
	 * Applies to new documents. A file's own frontmatter always wins.
	 */
	projectLanguageHint: () => LocalizedString
	/**
	 * Done
	 */
	done: () => LocalizedString
	/**
	 * This folder is not a Sietch project
	 */
	errorNotProject: () => LocalizedString
	/**
	 * Recent projects
	 */
	recentProjects: () => LocalizedString
	/**
	 * Remove from recents
	 */
	removeFromRecents: () => LocalizedString
	/**
	 * Your latest changes could not be saved. Close anyway and lose them?
	 */
	saveFailedCloseAnyway: () => LocalizedString
}

export type Formatters = {}
