// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * L​i​b​r​a​r​y
	 */
	library: string
	/**
	 * V​i​e​w
	 */
	view: string
	/**
	 * +
	 */
	newDocument: string
	/**
	 * N​e​w​ ​c​h​a​p​t​e​r
	 */
	newChapterLabel: string
	/**
	 * N​e​w​ ​f​o​l​d​e​r
	 */
	newFolder: string
	/**
	 * F​o​l​d​e​r
	 */
	folder: string
	/**
	 * F​o​l​d​e​r​ ​t​i​t​l​e
	 */
	folderTitleLabel: string
	/**
	 * D​e​l​e​t​e​ ​f​o​l​d​e​r
	 */
	deleteFolder: string
	/**
	 * R​e​n​a​m​e
	 */
	rename: string
	/**
	 * D​e​l​e​t​e​ ​c​h​a​p​t​e​r
	 */
	deleteChapter: string
	/**
	 * E​x​p​a​n​d
	 */
	expandFolder: string
	/**
	 * C​o​l​l​a​p​s​e
	 */
	collapseFolder: string
	/**
	 * M​o​v​e​d​ ​{​t​i​t​l​e​}​ ​t​o​ ​{​p​o​s​i​t​i​o​n​}​ ​o​f​ ​{​t​o​t​a​l​}​ ​i​n​ ​{​p​a​r​e​n​t​}
	 * @param {string} parent
	 * @param {number} position
	 * @param {string} title
	 * @param {number} total
	 */
	treeMoved: RequiredParams<'parent' | 'position' | 'title' | 'total'>
	/**
	 * t​h​e​ ​t​o​p​ ​l​e​v​e​l
	 */
	topLevel: string
	/**
	 * D​e​l​e​t​e​ ​{​t​i​t​l​e​}​ ​a​n​d​ ​t​h​e​ ​{​c​o​u​n​t​}​ ​c​h​a​p​t​e​r​s​ ​i​n​s​i​d​e​ ​i​t​?​ ​T​h​e​y​ ​m​o​v​e​ ​t​o​ ​t​h​e​ ​p​r​o​j​e​c​t​'​s​ ​t​r​a​s​h​ ​f​o​l​d​e​r​.
	 * @param {number} count
	 * @param {string} title
	 */
	deleteFolderConfirm: RequiredParams<'count' | 'title'>
	/**
	 * M​o​v​e​d​ ​{​t​i​t​l​e​}​ ​t​o​ ​t​h​e​ ​t​r​a​s​h
	 * @param {string} title
	 */
	chapterTrashed: RequiredParams<'title'>
	/**
	 * D​e​l​e​t​e​d​ ​{​t​i​t​l​e​}​ ​a​n​d​ ​m​o​v​e​d​ ​{​c​o​u​n​t​}​ ​c​h​a​p​t​e​r​s​ ​t​o​ ​t​h​e​ ​t​r​a​s​h
	 * @param {number} count
	 * @param {string} title
	 */
	folderTrashed: RequiredParams<'count' | 'title'>
	/**
	 * U​n​t​i​t​l​e​d​ ​P​r​o​j​e​c​t
	 */
	projectTitle: string
	/**
	 * N​o​t​h​i​n​g​ ​h​e​r​e
	 */
	viewEmpty: string
	/**
	 * T​r​a​s​h
	 */
	trash: string
	/**
	 * R​e​s​t​o​r​e
	 */
	restore: string
	/**
	 * D​e​l​e​t​e​d​ ​{​w​h​e​n​}
	 * @param {string} when
	 */
	deletedAgo: RequiredParams<'when'>
	/**
	 * I​n​ ​t​h​e​ ​t​r​a​s​h
	 */
	inTheTrash: string
	/**
	 * R​e​s​t​o​r​e​d​ ​{​t​i​t​l​e​}​ ​t​o​ ​t​h​e​ ​t​o​p​ ​l​e​v​e​l
	 * @param {string} title
	 */
	chapterRestored: RequiredParams<'title'>
	/**
	 * B​e​g​i​n​ ​w​r​i​t​i​n​g​.​.​.
	 */
	placeholder: string
	/**
	 * U​n​t​i​t​l​e​d
	 */
	untitled: string
	/**
	 * C​h​a​p​t​e​r​ ​{​n​}
	 * @param {number} n
	 */
	chapterEyebrow: RequiredParams<'n'>
	/**
	 * C​h​a​p​t​e​r​ ​t​i​t​l​e
	 */
	chapterTitleLabel: string
	/**
	 * J​u​s​t​ ​n​o​w
	 */
	justNow: string
	/**
	 * {​m​i​n​u​t​e​s​}​ ​m​i​n
	 * @param {number} minutes
	 */
	readingTime: RequiredParams<'minutes'>
	/**
	 * T​h​i​s​ ​d​o​c​u​m​e​n​t​ ​c​h​a​n​g​e​d​ ​o​u​t​s​i​d​e​ ​F​u​l​g​u​r​i​t​a​.
	 */
	changedOnDisk: string
	/**
	 * R​e​l​o​a​d
	 */
	reloadFromDisk: string
	/**
	 * K​e​e​p​ ​m​i​n​e
	 */
	keepMine: string
	/**
	 * F​o​r​m​a​t​t​i​n​g
	 */
	formatToolbarLabel: string
	/**
	 * B​o​l​d
	 */
	fmtBold: string
	/**
	 * I​t​a​l​i​c
	 */
	fmtItalic: string
	/**
	 * B​l​o​c​k​q​u​o​t​e
	 */
	fmtBlockquote: string
	/**
	 * B​u​l​l​e​t​ ​l​i​s​t
	 */
	fmtBulletList: string
	/**
	 * I​n​l​i​n​e​ ​c​o​d​e
	 */
	fmtCode: string
	/**
	 * P​a​r​a​g​r​a​p​h​ ​s​t​y​l​e
	 */
	styleDropdownLabel: string
	/**
	 * S​t​r​u​c​t​u​r​e
	 */
	styleGroupStructure: string
	/**
	 * S​t​y​l​e​s
	 */
	styleGroupSemantic: string
	/**
	 * N​o​ ​S​t​y​l​e
	 */
	styleNoStyle: string
	/**
	 * T​i​t​l​e
	 */
	styleTitle: string
	/**
	 * H​e​a​d​i​n​g​ ​1
	 */
	styleHeading1: string
	/**
	 * H​e​a​d​i​n​g​ ​2
	 */
	styleHeading2: string
	/**
	 * H​e​a​d​i​n​g​ ​3
	 */
	styleHeading3: string
	/**
	 * B​l​o​c​k​ ​Q​u​o​t​e
	 */
	styleBlockQuote: string
	/**
	 * C​o​d​e​ ​B​l​o​c​k
	 */
	styleCodeBlock: string
	/**
	 * A​t​t​r​i​b​u​t​i​o​n
	 */
	styleAttribution: string
	/**
	 * C​a​p​t​i​o​n
	 */
	styleCaption: string
	/**
	 * V​e​r​s​e
	 */
	styleVerse: string
	/**
	 * C​e​n​t​e​r​e​d​ ​T​e​x​t
	 */
	styleCentered: string
	/**
	 * S​y​n​o​p​s​i​s
	 */
	synopsis: string
	/**
	 * W​h​a​t​ ​h​a​p​p​e​n​s​ ​i​n​ ​t​h​i​s​ ​c​h​a​p​t​e​r​?
	 */
	synopsisPlaceholder: string
	/**
	 * S​t​a​t​i​s​t​i​c​s
	 */
	statistics: string
	/**
	 * O​u​t​l​i​n​e
	 */
	outline: string
	/**
	 * N​o​t​e​s
	 */
	notes: string
	/**
	 * J​o​t​ ​d​o​w​n​ ​i​d​e​a​s​,​ ​r​e​m​i​n​d​e​r​s​.​.​.
	 */
	notesPlaceholder: string
	/**
	 * W​o​r​d​s
	 */
	words: string
	/**
	 * C​h​a​r​a​c​t​e​r​s
	 */
	characters: string
	/**
	 * P​a​r​a​g​r​a​p​h​s
	 */
	paragraphs: string
	/**
	 * R​e​a​d​i​n​g​ ​T​i​m​e
	 */
	readingTimeLabel: string
	/**
	 * T​a​g​s
	 */
	tags: string
	/**
	 * A​d​d​ ​a​ ​t​a​g
	 */
	addTag: string
	/**
	 * P​O​V​,​ ​s​u​b​p​l​o​t​,​ ​t​i​m​e​l​i​n​e​…
	 */
	addTagPlaceholder: string
	/**
	 * R​e​m​o​v​e​ ​{​t​a​g​}
	 * @param {string} tag
	 */
	removeTag: RequiredParams<'tag'>
	/**
	 * C​o​l​o​r​ ​o​f​ ​{​t​a​g​}
	 * @param {string} tag
	 */
	tagColorLabel: RequiredParams<'tag'>
	/**
	 * D​e​f​a​u​l​t
	 */
	tagColorDefault: string
	/**
	 * C​l​a​y
	 */
	tagColorClay: string
	/**
	 * O​l​i​v​e
	 */
	tagColorOlive: string
	/**
	 * W​a​t​e​r
	 */
	tagColorWater: string
	/**
	 * P​l​u​m
	 */
	tagColorPlum: string
	/**
	 * E​m​b​e​r
	 */
	tagColorEmber: string
	/**
	 * S​k​y
	 */
	tagColorSky: string
	/**
	 * {​c​o​u​n​t​}​ ​w​o​r​d​s
	 * @param {number} count
	 */
	wordCount: RequiredParams<'count'>
	/**
	 * {​c​o​u​n​t​}​ ​/​ ​{​t​o​t​a​l​}​ ​w​o​r​d​s
	 * @param {string} count
	 * @param {string} total
	 */
	wordCountOf: RequiredParams<'count' | 'total'>
	/**
	 * ~​{​c​o​u​n​t​}​ ​{​{​p​a​g​e​|​p​a​g​e​s​}​}
	 * @param {string} count
	 */
	pageCount: RequiredParams<'count'>
	/**
	 * E​s​t​i​m​a​t​e​:​ ​~​{​t​r​a​d​e​}​ ​p​a​g​e​s​ ​i​n​ ​6​×​9​,​ ​~​{​m​a​n​u​s​c​r​i​p​t​}​ ​i​n​ ​m​a​n​u​s​c​r​i​p​t​ ​f​o​r​m​a​t​.
	 * @param {string} manuscript
	 * @param {string} trade
	 */
	pageEstimateHint: RequiredParams<'manuscript' | 'trade'>
	/**
	 * {​c​o​u​n​t​}​ ​s​e​s​s​i​o​n
	 * @param {string} count
	 */
	sessionWords: RequiredParams<'count'>
	/**
	 * {​t​i​m​e​}​ ​r​e​a​d
	 * @param {string} time
	 */
	readTimeStatus: RequiredParams<'time'>
	/**
	 * {​c​u​r​r​e​n​t​}​ ​/​ ​{​g​o​a​l​}
	 * @param {string} current
	 * @param {string} goal
	 */
	goalProgress: RequiredParams<'current' | 'goal'>
	/**
	 * S​a​v​e​d
	 */
	saveStateSaved: string
	/**
	 * S​a​v​e​d​ ​{​t​i​m​e​}
	 * @param {string} time
	 */
	saveStateSavedAt: RequiredParams<'time'>
	/**
	 * S​a​v​i​n​g​…
	 */
	saveStateSaving: string
	/**
	 * E​r​r​o​r
	 */
	saveStateError: string
	/**
	 * T​y​p​e​ ​a​ ​c​o​m​m​a​n​d​.​.​.
	 */
	commandPlaceholder: string
	/**
	 * G​o​ ​t​o​ ​c​h​a​p​t​e​r​.​.​.
	 */
	chapterPlaceholder: string
	/**
	 * N​e​w​ ​D​o​c​u​m​e​n​t
	 */
	cmdNewDocument: string
	/**
	 * O​p​e​n​ ​C​h​a​p​t​e​r​…
	 */
	cmdOpenChapter: string
	/**
	 * S​a​v​e
	 */
	cmdSave: string
	/**
	 * T​o​g​g​l​e​ ​S​i​d​e​b​a​r
	 */
	cmdToggleSidebar: string
	/**
	 * T​o​g​g​l​e​ ​I​n​s​p​e​c​t​o​r
	 */
	cmdToggleInspector: string
	/**
	 * T​o​g​g​l​e​ ​F​o​c​u​s​ ​M​o​d​e
	 */
	cmdToggleFocusMode: string
	/**
	 * T​o​g​g​l​e​ ​T​h​e​m​e
	 */
	cmdToggleTheme: string
	/**
	 * S​e​t​t​i​n​g​s​…
	 */
	cmdSettings: string
	/**
	 * D​o​c​u​m​e​n​t
	 */
	catDocument: string
	/**
	 * V​i​e​w
	 */
	catView: string
	/**
	 * P​r​o​j​e​c​t
	 */
	catProject: string
	/**
	 * T​o​g​g​l​e​ ​t​h​e​m​e
	 */
	toggleThemeLabel: string
	/**
	 * L​i​g​h​t
	 */
	themeDay: string
	/**
	 * D​a​r​k
	 */
	themeNight: string
	/**
	 * F​o​c​u​s​ ​M​o​d​e
	 */
	focusModeLabel: string
	/**
	 * W​e​l​c​o​m​e​ ​t​o​ ​F​u​l​g​u​r​i​t​a
	 */
	welcomeTitle: string
	/**
	 * A​ ​q​u​i​e​t​ ​p​l​a​c​e​ ​t​o​ ​w​r​i​t​e​.
	 */
	welcomeSubtitle: string
	/**
	 * C​r​e​a​t​e​ ​P​r​o​j​e​c​t
	 */
	createProject: string
	/**
	 * O​p​e​n​ ​P​r​o​j​e​c​t
	 */
	openProject: string
	/**
	 * P​r​o​j​e​c​t​ ​n​a​m​e
	 */
	projectNameLabel: string
	/**
	 * M​y​ ​N​o​v​e​l
	 */
	projectNamePlaceholder: string
	/**
	 * C​r​e​a​t​e
	 */
	create: string
	/**
	 * C​a​n​c​e​l
	 */
	cancel: string
	/**
	 * S​e​t​t​i​n​g​s
	 */
	settingsTitle: string
	/**
	 * P​r​o​j​e​c​t
	 */
	settingsSectionProject: string
	/**
	 * A​p​p​l​i​c​a​t​i​o​n
	 */
	settingsSectionApp: string
	/**
	 * P​r​o​j​e​c​t​ ​l​a​n​g​u​a​g​e
	 */
	projectLanguageLabel: string
	/**
	 * A​p​p​l​i​e​s​ ​t​o​ ​n​e​w​ ​d​o​c​u​m​e​n​t​s​.​ ​A​ ​f​i​l​e​'​s​ ​o​w​n​ ​f​r​o​n​t​m​a​t​t​e​r​ ​a​l​w​a​y​s​ ​w​i​n​s​.
	 */
	projectLanguageHint: string
	/**
	 * P​r​o​j​e​c​t​ ​t​y​p​e
	 */
	projectTypeLabel: string
	/**
	 * W​h​a​t​ ​k​i​n​d​ ​o​f​ ​w​r​i​t​i​n​g​ ​t​h​i​s​ ​p​r​o​j​e​c​t​ ​h​o​l​d​s​.​ ​N​e​w​ ​d​o​c​u​m​e​n​t​s​ ​a​n​d​ ​e​x​p​o​r​t​ ​k​e​e​p​ ​t​h​e​i​r​ ​o​w​n​ ​s​e​t​t​i​n​g​s​ ​f​o​r​ ​n​o​w​.
	 */
	projectTypeHint: string
	/**
	 * N​o​v​e​l
	 */
	projectTypeNovel: string
	/**
	 * L​o​n​g​f​o​r​m
	 */
	projectTypeLongform: string
	/**
	 * T​h​e​s​i​s
	 */
	projectTypeThesis: string
	/**
	 * B​l​o​g
	 */
	projectTypeBlog: string
	/**
	 * D​a​i​l​y​ ​w​o​r​d​ ​g​o​a​l
	 */
	dailyGoalLabel: string
	/**
	 * M​e​a​s​u​r​e​d​ ​a​g​a​i​n​s​t​ ​w​h​a​t​ ​y​o​u​ ​h​a​v​e​ ​w​r​i​t​t​e​n​ ​s​i​n​c​e​ ​o​p​e​n​i​n​g​ ​t​h​e​ ​p​r​o​j​e​c​t​.
	 */
	dailyGoalHint: string
	/**
	 * T​y​p​e​w​r​i​t​e​r​ ​s​c​r​o​l​l​i​n​g
	 */
	typewriterLabel: string
	/**
	 * O​f​f
	 */
	typewriterOff: string
	/**
	 * I​n​ ​f​o​c​u​s​ ​m​o​d​e
	 */
	typewriterInFocus: string
	/**
	 * K​e​e​p​s​ ​t​h​e​ ​l​i​n​e​ ​y​o​u​ ​a​r​e​ ​w​r​i​t​i​n​g​ ​n​e​a​r​ ​t​h​e​ ​m​i​d​d​l​e​ ​o​f​ ​t​h​e​ ​w​i​n​d​o​w​.
	 */
	typewriterHint: string
	/**
	 * I​n​t​e​r​f​a​c​e​ ​l​a​n​g​u​a​g​e
	 */
	appLanguageLabel: string
	/**
	 * A​p​p​l​i​e​s​ ​t​h​e​ ​n​e​x​t​ ​t​i​m​e​ ​F​u​l​g​u​r​i​t​a​ ​s​t​a​r​t​s​.
	 */
	appLanguageHint: string
	/**
	 * R​e​s​t​a​r​t​ ​F​u​l​g​u​r​i​t​a​ ​t​o​ ​s​e​e​ ​t​h​e​ ​i​n​t​e​r​f​a​c​e​ ​i​n​ ​t​h​i​s​ ​l​a​n​g​u​a​g​e​.
	 */
	appLanguageRestart: string
	/**
	 * R​e​s​t​a​r​t​ ​F​u​l​g​u​r​i​t​a​ ​n​o​w​ ​t​o​ ​a​p​p​l​y​ ​t​h​e​ ​n​e​w​ ​i​n​t​e​r​f​a​c​e​ ​l​a​n​g​u​a​g​e​?
	 */
	restartPrompt: string
	/**
	 * R​e​s​t​a​r​t​ ​n​o​w
	 */
	restartNow: string
	/**
	 * L​a​t​e​r
	 */
	restartLater: string
	/**
	 * D​o​n​e
	 */
	done: string
	/**
	 * T​h​i​s​ ​f​o​l​d​e​r​ ​i​s​ ​n​o​t​ ​a​ ​F​u​l​g​u​r​i​t​a​ ​p​r​o​j​e​c​t
	 */
	errorNotProject: string
	/**
	 * R​e​c​e​n​t​ ​p​r​o​j​e​c​t​s
	 */
	recentProjects: string
	/**
	 * R​e​m​o​v​e​ ​f​r​o​m​ ​r​e​c​e​n​t​s
	 */
	removeFromRecents: string
	/**
	 * Y​o​u​r​ ​l​a​t​e​s​t​ ​c​h​a​n​g​e​s​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​s​a​v​e​d​.​ ​C​l​o​s​e​ ​a​n​y​w​a​y​ ​a​n​d​ ​l​o​s​e​ ​t​h​e​m​?
	 */
	saveFailedCloseAnyway: string
	/**
	 * Y​o​u​r​ ​l​a​t​e​s​t​ ​c​h​a​n​g​e​s​ ​c​o​u​l​d​ ​n​o​t​ ​b​e​ ​s​a​v​e​d​.​ ​R​e​s​t​a​r​t​ ​a​n​y​w​a​y​ ​a​n​d​ ​l​o​s​e​ ​t​h​e​m​?
	 */
	saveFailedRestartAnyway: string
}

export type TranslationFunctions = {
	/**
	 * Library
	 */
	library: () => LocalizedString
	/**
	 * View
	 */
	view: () => LocalizedString
	/**
	 * +
	 */
	newDocument: () => LocalizedString
	/**
	 * New chapter
	 */
	newChapterLabel: () => LocalizedString
	/**
	 * New folder
	 */
	newFolder: () => LocalizedString
	/**
	 * Folder
	 */
	folder: () => LocalizedString
	/**
	 * Folder title
	 */
	folderTitleLabel: () => LocalizedString
	/**
	 * Delete folder
	 */
	deleteFolder: () => LocalizedString
	/**
	 * Rename
	 */
	rename: () => LocalizedString
	/**
	 * Delete chapter
	 */
	deleteChapter: () => LocalizedString
	/**
	 * Expand
	 */
	expandFolder: () => LocalizedString
	/**
	 * Collapse
	 */
	collapseFolder: () => LocalizedString
	/**
	 * Moved {title} to {position} of {total} in {parent}
	 */
	treeMoved: (arg: { parent: string, position: number, title: string, total: number }) => LocalizedString
	/**
	 * the top level
	 */
	topLevel: () => LocalizedString
	/**
	 * Delete {title} and the {count} chapters inside it? They move to the project's trash folder.
	 */
	deleteFolderConfirm: (arg: { count: number, title: string }) => LocalizedString
	/**
	 * Moved {title} to the trash
	 */
	chapterTrashed: (arg: { title: string }) => LocalizedString
	/**
	 * Deleted {title} and moved {count} chapters to the trash
	 */
	folderTrashed: (arg: { count: number, title: string }) => LocalizedString
	/**
	 * Untitled Project
	 */
	projectTitle: () => LocalizedString
	/**
	 * Nothing here
	 */
	viewEmpty: () => LocalizedString
	/**
	 * Trash
	 */
	trash: () => LocalizedString
	/**
	 * Restore
	 */
	restore: () => LocalizedString
	/**
	 * Deleted {when}
	 */
	deletedAgo: (arg: { when: string }) => LocalizedString
	/**
	 * In the trash
	 */
	inTheTrash: () => LocalizedString
	/**
	 * Restored {title} to the top level
	 */
	chapterRestored: (arg: { title: string }) => LocalizedString
	/**
	 * Begin writing...
	 */
	placeholder: () => LocalizedString
	/**
	 * Untitled
	 */
	untitled: () => LocalizedString
	/**
	 * Chapter {n}
	 */
	chapterEyebrow: (arg: { n: number }) => LocalizedString
	/**
	 * Chapter title
	 */
	chapterTitleLabel: () => LocalizedString
	/**
	 * Just now
	 */
	justNow: () => LocalizedString
	/**
	 * {minutes} min
	 */
	readingTime: (arg: { minutes: number }) => LocalizedString
	/**
	 * This document changed outside Fulgurita.
	 */
	changedOnDisk: () => LocalizedString
	/**
	 * Reload
	 */
	reloadFromDisk: () => LocalizedString
	/**
	 * Keep mine
	 */
	keepMine: () => LocalizedString
	/**
	 * Formatting
	 */
	formatToolbarLabel: () => LocalizedString
	/**
	 * Bold
	 */
	fmtBold: () => LocalizedString
	/**
	 * Italic
	 */
	fmtItalic: () => LocalizedString
	/**
	 * Blockquote
	 */
	fmtBlockquote: () => LocalizedString
	/**
	 * Bullet list
	 */
	fmtBulletList: () => LocalizedString
	/**
	 * Inline code
	 */
	fmtCode: () => LocalizedString
	/**
	 * Paragraph style
	 */
	styleDropdownLabel: () => LocalizedString
	/**
	 * Structure
	 */
	styleGroupStructure: () => LocalizedString
	/**
	 * Styles
	 */
	styleGroupSemantic: () => LocalizedString
	/**
	 * No Style
	 */
	styleNoStyle: () => LocalizedString
	/**
	 * Title
	 */
	styleTitle: () => LocalizedString
	/**
	 * Heading 1
	 */
	styleHeading1: () => LocalizedString
	/**
	 * Heading 2
	 */
	styleHeading2: () => LocalizedString
	/**
	 * Heading 3
	 */
	styleHeading3: () => LocalizedString
	/**
	 * Block Quote
	 */
	styleBlockQuote: () => LocalizedString
	/**
	 * Code Block
	 */
	styleCodeBlock: () => LocalizedString
	/**
	 * Attribution
	 */
	styleAttribution: () => LocalizedString
	/**
	 * Caption
	 */
	styleCaption: () => LocalizedString
	/**
	 * Verse
	 */
	styleVerse: () => LocalizedString
	/**
	 * Centered Text
	 */
	styleCentered: () => LocalizedString
	/**
	 * Synopsis
	 */
	synopsis: () => LocalizedString
	/**
	 * What happens in this chapter?
	 */
	synopsisPlaceholder: () => LocalizedString
	/**
	 * Statistics
	 */
	statistics: () => LocalizedString
	/**
	 * Outline
	 */
	outline: () => LocalizedString
	/**
	 * Notes
	 */
	notes: () => LocalizedString
	/**
	 * Jot down ideas, reminders...
	 */
	notesPlaceholder: () => LocalizedString
	/**
	 * Words
	 */
	words: () => LocalizedString
	/**
	 * Characters
	 */
	characters: () => LocalizedString
	/**
	 * Paragraphs
	 */
	paragraphs: () => LocalizedString
	/**
	 * Reading Time
	 */
	readingTimeLabel: () => LocalizedString
	/**
	 * Tags
	 */
	tags: () => LocalizedString
	/**
	 * Add a tag
	 */
	addTag: () => LocalizedString
	/**
	 * POV, subplot, timeline…
	 */
	addTagPlaceholder: () => LocalizedString
	/**
	 * Remove {tag}
	 */
	removeTag: (arg: { tag: string }) => LocalizedString
	/**
	 * Color of {tag}
	 */
	tagColorLabel: (arg: { tag: string }) => LocalizedString
	/**
	 * Default
	 */
	tagColorDefault: () => LocalizedString
	/**
	 * Clay
	 */
	tagColorClay: () => LocalizedString
	/**
	 * Olive
	 */
	tagColorOlive: () => LocalizedString
	/**
	 * Water
	 */
	tagColorWater: () => LocalizedString
	/**
	 * Plum
	 */
	tagColorPlum: () => LocalizedString
	/**
	 * Ember
	 */
	tagColorEmber: () => LocalizedString
	/**
	 * Sky
	 */
	tagColorSky: () => LocalizedString
	/**
	 * {count} words
	 */
	wordCount: (arg: { count: number }) => LocalizedString
	/**
	 * {count} / {total} words
	 */
	wordCountOf: (arg: { count: string, total: string }) => LocalizedString
	/**
	 * ~{count} {{page|pages}}
	 */
	pageCount: (arg: { count: string, pages: number | string | boolean }) => LocalizedString
	/**
	 * Estimate: ~{trade} pages in 6×9, ~{manuscript} in manuscript format.
	 */
	pageEstimateHint: (arg: { manuscript: string, trade: string }) => LocalizedString
	/**
	 * {count} session
	 */
	sessionWords: (arg: { count: string }) => LocalizedString
	/**
	 * {time} read
	 */
	readTimeStatus: (arg: { time: string }) => LocalizedString
	/**
	 * {current} / {goal}
	 */
	goalProgress: (arg: { current: string, goal: string }) => LocalizedString
	/**
	 * Saved
	 */
	saveStateSaved: () => LocalizedString
	/**
	 * Saved {time}
	 */
	saveStateSavedAt: (arg: { time: string }) => LocalizedString
	/**
	 * Saving…
	 */
	saveStateSaving: () => LocalizedString
	/**
	 * Error
	 */
	saveStateError: () => LocalizedString
	/**
	 * Type a command...
	 */
	commandPlaceholder: () => LocalizedString
	/**
	 * Go to chapter...
	 */
	chapterPlaceholder: () => LocalizedString
	/**
	 * New Document
	 */
	cmdNewDocument: () => LocalizedString
	/**
	 * Open Chapter…
	 */
	cmdOpenChapter: () => LocalizedString
	/**
	 * Save
	 */
	cmdSave: () => LocalizedString
	/**
	 * Toggle Sidebar
	 */
	cmdToggleSidebar: () => LocalizedString
	/**
	 * Toggle Inspector
	 */
	cmdToggleInspector: () => LocalizedString
	/**
	 * Toggle Focus Mode
	 */
	cmdToggleFocusMode: () => LocalizedString
	/**
	 * Toggle Theme
	 */
	cmdToggleTheme: () => LocalizedString
	/**
	 * Settings…
	 */
	cmdSettings: () => LocalizedString
	/**
	 * Document
	 */
	catDocument: () => LocalizedString
	/**
	 * View
	 */
	catView: () => LocalizedString
	/**
	 * Project
	 */
	catProject: () => LocalizedString
	/**
	 * Toggle theme
	 */
	toggleThemeLabel: () => LocalizedString
	/**
	 * Light
	 */
	themeDay: () => LocalizedString
	/**
	 * Dark
	 */
	themeNight: () => LocalizedString
	/**
	 * Focus Mode
	 */
	focusModeLabel: () => LocalizedString
	/**
	 * Welcome to Fulgurita
	 */
	welcomeTitle: () => LocalizedString
	/**
	 * A quiet place to write.
	 */
	welcomeSubtitle: () => LocalizedString
	/**
	 * Create Project
	 */
	createProject: () => LocalizedString
	/**
	 * Open Project
	 */
	openProject: () => LocalizedString
	/**
	 * Project name
	 */
	projectNameLabel: () => LocalizedString
	/**
	 * My Novel
	 */
	projectNamePlaceholder: () => LocalizedString
	/**
	 * Create
	 */
	create: () => LocalizedString
	/**
	 * Cancel
	 */
	cancel: () => LocalizedString
	/**
	 * Settings
	 */
	settingsTitle: () => LocalizedString
	/**
	 * Project
	 */
	settingsSectionProject: () => LocalizedString
	/**
	 * Application
	 */
	settingsSectionApp: () => LocalizedString
	/**
	 * Project language
	 */
	projectLanguageLabel: () => LocalizedString
	/**
	 * Applies to new documents. A file's own frontmatter always wins.
	 */
	projectLanguageHint: () => LocalizedString
	/**
	 * Project type
	 */
	projectTypeLabel: () => LocalizedString
	/**
	 * What kind of writing this project holds. New documents and export keep their own settings for now.
	 */
	projectTypeHint: () => LocalizedString
	/**
	 * Novel
	 */
	projectTypeNovel: () => LocalizedString
	/**
	 * Longform
	 */
	projectTypeLongform: () => LocalizedString
	/**
	 * Thesis
	 */
	projectTypeThesis: () => LocalizedString
	/**
	 * Blog
	 */
	projectTypeBlog: () => LocalizedString
	/**
	 * Daily word goal
	 */
	dailyGoalLabel: () => LocalizedString
	/**
	 * Measured against what you have written since opening the project.
	 */
	dailyGoalHint: () => LocalizedString
	/**
	 * Typewriter scrolling
	 */
	typewriterLabel: () => LocalizedString
	/**
	 * Off
	 */
	typewriterOff: () => LocalizedString
	/**
	 * In focus mode
	 */
	typewriterInFocus: () => LocalizedString
	/**
	 * Keeps the line you are writing near the middle of the window.
	 */
	typewriterHint: () => LocalizedString
	/**
	 * Interface language
	 */
	appLanguageLabel: () => LocalizedString
	/**
	 * Applies the next time Fulgurita starts.
	 */
	appLanguageHint: () => LocalizedString
	/**
	 * Restart Fulgurita to see the interface in this language.
	 */
	appLanguageRestart: () => LocalizedString
	/**
	 * Restart Fulgurita now to apply the new interface language?
	 */
	restartPrompt: () => LocalizedString
	/**
	 * Restart now
	 */
	restartNow: () => LocalizedString
	/**
	 * Later
	 */
	restartLater: () => LocalizedString
	/**
	 * Done
	 */
	done: () => LocalizedString
	/**
	 * This folder is not a Fulgurita project
	 */
	errorNotProject: () => LocalizedString
	/**
	 * Recent projects
	 */
	recentProjects: () => LocalizedString
	/**
	 * Remove from recents
	 */
	removeFromRecents: () => LocalizedString
	/**
	 * Your latest changes could not be saved. Close anyway and lose them?
	 */
	saveFailedCloseAnyway: () => LocalizedString
	/**
	 * Your latest changes could not be saved. Restart anyway and lose them?
	 */
	saveFailedRestartAnyway: () => LocalizedString
}

export type Formatters = {}
